"""add email

Revision ID: 6e58168d74a9
Revises: 
Create Date: 2020-03-26 15:04:23.475345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e58168d74a9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.String(length=50), nullable=True))
    op.create_unique_constraint(None, 'user', ['email'])
    op.add_column('weather', sa.Column('temp_C', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'weather', ['city'])
    op.drop_column('weather', 'temp_c')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weather', sa.Column('temp_c', sa.INTEGER(), nullable=False))
    op.drop_constraint(None, 'weather', type_='unique')
    op.drop_column('weather', 'temp_C')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'email')
    # ### end Alembic commands ###
